module.exports = [
  "Алим", // Apple
  "Нар", // Sun
  "Морь", // Horse
  "Гэр", // Yurt/Home
  "Тэнгэр", // Sky
  "Ус", // Water
  "Гал", // Fire
  "Ном", // Book
  "Цэцэг", // Flower
  "Ширээ", // Table
  "Сандал", // Chair
  "Хаалга", // Door
  "Цонх", // Window
  "Машин", // Car
  "Нохой", // Dog
  "Муур", // Cat
  "Багш", // Teacher
  "Оюутан", // Student
  "Эмч", // Doctor
  "Цагдаа", // Police
  "Сургууль", // School
  "Аав", // Father
  "Ээж", // Mother
  "Найз", // Friend
  "Хайр", // Love
  "Мөнгө", // Money
  "Ажил", // Job
  "Компьютер", // Computer
  "Утас", // Phone
  "Цас", // Snow
  "Бороо", // Rain
];
